build_images:
  stage: build
  script:
    - sudo docker compose build

deploy_to_gcp:
  stage: deploy
  script:
    - sudo docker container stop enhancergenie-client-1 || true
    - sudo docker container stop enhancergenie-api-1 || true
    - sudo docker rm enhancergenie-client-1 || true
    - sudo docker rm enhancergenie-api-1 || true

    - sudo docker compose up -d
    - sudo docker run -dp 8080:8080 --name enhancergenie-api-1 enhancergenie-api-1
    - sudo docker run -dp 3000:3000 --name enhancergenie-client-1 enhancergenie-client-1
    - sudo docker image prune -af
    - sudo docker system prune -f
