stages:
  - build
  - deploy

services:
  - docker:dind

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info
  - docker-compose --version

build_images:
  stage: build
  script:
    - docker-compose build
  only:
    - main

deploy_to_ec2:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no ec2-user@3.23.108.127 <<EOF
        cd ./enhancerGenie
        git pull
        docker-compose down
        docker-compose up -d
      EOF
  only:
    - main
