stages:
  - build
  - deploy

build_images:
  stage: build
  script:
    - /usr/local/bin/docker-compose build
  only:
    - main

deploy_to_ec2:
  stage: deploy
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no ec2-user@3.23.108.127 <<EOF
        cd ./enhancerGenie
        git pull
        /usr/local/bin/docker-compose down
        /usr/local/bin/docker-compose up -d
      EOF
  only:
    - main
