build_images:
  stage: build
  script:
    - sudo docker compose build

deploy_to_gcp:
  stage: deploy
  script:
    - sudo docker container stop enhancer-gene-pro-frontend || true
    - sudo docker container stop enhancer-gene-pro-backend || true
    - sudo docker rm enhancer-gene-pro-frontend || true
    - sudo docker rm enhancer-gene-pro-backend || true
    - sudo docker compose up -d
    - sudo docker run -dp 8080:8080 --name enhancer-gene-pro-backend enhancer-gene-pro-backend
    - sudo docker run -dp 3000:3000 --name enhancer-gene-pro-frontend enhancer-gene-pro-frontend
    - sudo docker image prune -af
    - sudo docker system prune -f
