stages:
  - build
  - deploy

variables:
  DOCKER_HOST: "unix:///var/run/docker.sock"
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - docker info
  - docker-compose --version

build_images:
  stage: build
  image: docker:20.10.7
  script:
    - docker-compose build
  only:
    - main

deploy_to_ec2:
  stage: deploy
  image: docker:20.10.7
  script:
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$DEPLOY_PRIVATE_KEY")
    - ssh -o StrictHostKeyChecking=no ec2-user@3.23.108.127 <<EOF
        cd ./myproject
        git pull
        docker-compose down
        docker-compose up -d
      EOF
  only:
    - main
