variables:
  DOCKER_HOST: "tcp://docker:2375"
  DOCKER_TLS_CERTDIR: ""

stages:
  - build
  - deploy

build_images:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  variables:
    CI_DEBUG_TRACE: "true"
  script:
    - docker info || true
    - docker-compose --version
    - docker-compose build
  only:
    - main

deploy_to_ec2:
  stage: deploy
  image: docker:latest
  before_script:
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan -H '3.23.108.127' >> ~/.ssh/known_hosts
  script:
    - ssh -o StrictHostKeyChecking=no ec2-user@3.23.108.127 'bash -s' <<EOF
        cd myproject
        git pull
        docker-compose down
        docker-compose up -d
      EOF
  only:
    - main
