stages:
  - build
  - deploy

build_images:
  stage: build
  image: docker:latest
  script:
    - docker-compose --version
    - docker-compose build

deploy_to_gcp:
  stage: deploy
  script:
    - docker-compose up -d
  environment:
    name: production
    url: http://34.174.221.175
