build_images:
  stage: build
  before_script:
  - sudo chmod -R 777 frontend/node_modules
  script:
    - sudo docker compose build

deploy_to_gcp:
  stage: deploy
  script:
    - sudo docker compose down
    - sudo docker compose up -d
    - sudo docker image prune -af
    - sudo docker system prune -f
